# Generated by Django 5.2.7 on 2026-01-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_item_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sku',
            new_name='sn',
        ),
    ]
